Repository cnieg/helm-charts, pull requests merged in 2020-08, with the labels that each got.

#28 feat(castelmock): init chart
  .github/workflows/helm.yaml
  charts/castlemock/.helmignore
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/NOTES.txt
  charts/castlemock/templates/_helpers.tpl
  charts/castlemock/templates/deployment.yaml
  charts/castlemock/templates/hpa.yaml
  charts/castlemock/templates/ingress.yaml
  charts/castlemock/templates/pvc.yaml
  charts/castlemock/templates/service.yaml
  charts/castlemock/templates/serviceaccount.yaml
  charts/castlemock/templates/tests/test-connection.yaml
  charts/castlemock/values.yaml
Labels: size/L

#29 fix: persistence usage in chart
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/deployment.yaml
  charts/castlemock/templates/ingress.yaml
  charts/castlemock/templates/pvc.yaml
  charts/castlemock/values.yaml
Labels: size/M

#30 [castlemock]: fix indent in labels for pvc
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/pvc.yaml
Labels: size/XS
