Repository cnieg/helm-charts, pull requests merged in 2020-09, with the labels that each got.

#32 fix(castlemock): #31 externalize livenessConf
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/deployment.yaml
  charts/castlemock/values.yaml
Labels: size/S

#33 [gantt] Update default app version
  charts/gantt/Chart.yaml
  charts/gantt/values.yaml
Labels: size/XS

#34 feat(pulsar): update pulsar version
  charts/pulsar/Chart.yaml
  charts/pulsar/values.yaml
Labels: size/M
