Repository cnieg/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#65 2021-11 update api versions and ingress
  charts/maildev/Chart.yaml
  charts/maildev/templates/cron.yaml
  charts/maildev/templates/ingress.yaml
  charts/maildev/values.yaml
Labels: size/M

#67 Upgrade Passbolt to latest v3
  charts/passbolt/Chart.yaml
  charts/passbolt/README.md
  charts/passbolt/templates/deployment.yaml
Labels: size/S

#68 Use latest docker image version
  charts/castlemock/Chart.yaml
Labels: size/XS

#69 fix(passbolt): Fix path to license file
  charts/passbolt/Chart.yaml
  charts/passbolt/templates/deployment.yaml
Labels: size/XS
