Repository cnieg/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#51 feat: add lua module
  charts/proxy-relay/Chart.yaml
  charts/proxy-relay/templates/configmap.yaml
  charts/proxy-relay/templates/deployment.yaml
  charts/proxy-relay/values.yaml
Labels: size/M

#52 fix(proxy-relay): Fix location of lua scripts
  charts/proxy-relay/Chart.yaml
  charts/proxy-relay/templates/configmap.yaml
Labels: size/XS

#53 feat(default-chart): Add default chart
  charts/default-chart/.helmignore
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/NOTES.txt
  charts/default-chart/templates/_helpers.tpl
  charts/default-chart/templates/deployment.yaml
  charts/default-chart/templates/ingress.yaml
  charts/default-chart/templates/service.yaml
  charts/default-chart/templates/serviceaccount.yaml
  charts/default-chart/templates/tests/test-connection.yaml
  charts/default-chart/values.yaml
Labels: size/L

#54 fix(default-chart): version can't be ovveride, fix this
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/_helpers.tpl
  charts/default-chart/templates/deployment.yaml
  charts/default-chart/values.yaml
Labels: size/S

#55 fix(default-chart): update keywork version to tag for dockar image
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/_helpers.tpl
  charts/default-chart/templates/deployment.yaml
  charts/default-chart/values.yaml
Labels: size/XS

#56 feat(default-chart): Add some customzation: PDB, PVC, HPA
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/deployment.yaml
  charts/default-chart/templates/horizontal-pod-autoscaler.yaml
  charts/default-chart/templates/persistent-volume-claim.yaml
  charts/default-chart/templates/pod-disruption-budget.yaml
  charts/default-chart/values.yaml
Labels: size/L

#57 fix(default-chart): PDB can't be disable, and add some values for tes…
  charts/default-chart/Chart.yaml
  charts/default-chart/ci/ci-values.yaml
  charts/default-chart/templates/pod-disruption-budget.yaml
Labels: size/M

#58 fix(default-chart): HPA can't be disabled
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/horizontal-pod-autoscaler.yaml
Labels: size/XS

#59 fix(default-chart): Container name can be renamed to nameOvveride
  charts/default-chart/Chart.yaml
  charts/default-chart/templates/deployment.yaml
Labels: size/XS
