Repository cnieg/helm-charts, pull requests merged in 2022-06, with the labels that each got.

#94 Fix dependencies maria and ci
  .github/workflows/helm.yaml
  charts/passbolt/Chart.yaml
Labels: size/M

#79 [FEAT] added ServiceAccount
  charts/passbolt/Chart.yaml
  charts/passbolt/templates/_helpers.tpl
  charts/passbolt/templates/deployment.yaml
  charts/passbolt/templates/serviceaccount.yaml
  charts/passbolt/values.yaml
Labels: size/M

#99 Update renovate.json
  renovate.json
Labels: size/XS

#101 Delete charts/pulsar directory
  charts/pulsar/.helmignore
  charts/pulsar/Chart.yaml
  charts/pulsar/ci/ci-values.yaml
  charts/pulsar/templates/_autorecovery.tpl
  charts/pulsar/templates/_bookkeeper.tpl
  charts/pulsar/templates/_broker.tpl
  charts/pulsar/templates/_helpers.tpl
  charts/pulsar/templates/_toolset.tpl
  charts/pulsar/templates/_zookeeper.tpl
  charts/pulsar/templates/autorecovery-configmap.yaml
  charts/pulsar/templates/autorecovery-service.yaml
  charts/pulsar/templates/autorecovery-statefulset.yaml
  charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
  charts/pulsar/templates/bookkeeper-configmap.yaml
  charts/pulsar/templates/bookkeeper-pdb.yaml
  charts/pulsar/templates/bookkeeper-service.yaml
  charts/pulsar/templates/bookkeeper-statefulset.yaml
  charts/pulsar/templates/bookkeeper-storageclass.yaml
  charts/pulsar/templates/broker-cluster-role-binding.yaml
  charts/pulsar/templates/broker-configmap.yaml
  charts/pulsar/templates/broker-pdb.yaml
  charts/pulsar/templates/broker-rbac.yaml
  charts/pulsar/templates/broker-service-account.yaml
  charts/pulsar/templates/broker-service.yaml
  charts/pulsar/templates/broker-statefulset.yaml
  charts/pulsar/templates/dashboard-deployment.yaml
  charts/pulsar/templates/dashboard-ingress.yaml
  charts/pulsar/templates/dashboard-service.yaml
  charts/pulsar/templates/function-worker-configmap.yaml
  charts/pulsar/templates/grafana-deployment.yaml
  charts/pulsar/templates/grafana-ingress.yaml
  charts/pulsar/templates/grafana-service.yaml
  charts/pulsar/templates/keytool.yaml
  charts/pulsar/templates/prometheus-configmap.yaml
  charts/pulsar/templates/prometheus-deployment.yaml
  charts/pulsar/templates/prometheus-pvc.yaml
  charts/pulsar/templates/prometheus-rbac.yaml
  charts/pulsar/templates/prometheus-service.yaml
  charts/pulsar/templates/prometheus-storageclass.yaml
  charts/pulsar/templates/proxy-configmap.yaml
  charts/pulsar/templates/proxy-pdb.yaml
  charts/pulsar/templates/proxy-service.yaml
  charts/pulsar/templates/proxy-statefulset.yaml
  charts/pulsar/templates/pulsar-cluster-initialize.yaml
  charts/pulsar/templates/pulsar-manager-admin-secret.yaml
  charts/pulsar/templates/pulsar-manager-configmap.yaml
  charts/pulsar/templates/pulsar-manager-deployment.yaml
  charts/pulsar/templates/pulsar-manager-ingress.yaml
  charts/pulsar/templates/pulsar-manager-service.yaml
  charts/pulsar/templates/tls-cert-internal-issuer.yaml
  charts/pulsar/templates/tls-certs-internal.yaml
  charts/pulsar/templates/toolset-configmap.yaml
  charts/pulsar/templates/toolset-service.yaml
  charts/pulsar/templates/toolset-statefulset.yaml
  charts/pulsar/templates/zookeeper-configmap.yaml
  charts/pulsar/templates/zookeeper-pdb.yaml
  charts/pulsar/templates/zookeeper-service.yaml
  charts/pulsar/templates/zookeeper-statefulset.yaml
  charts/pulsar/templates/zookeeper-storageclass.yaml
  charts/pulsar/values.yaml
Labels: size/XXL

#104 fix(castlemock): fix service back configuration for v1 ingress api
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/ingress.yaml
Labels: size/XS

#105 fix(castlemock): Use port name instead port number
  charts/castlemock/Chart.yaml
  charts/castlemock/templates/ingress.yaml
Labels: size/XS
